import enum


class RolClub(str, enum.Enum):
    """Coincide con el tipo ENUM `rol_club` definido en db/schema.sql."""

    GESTOR_CLUB = "GESTOR_CLUB"
    ENTRENADOR = "ENTRENADOR"
    AYUDANTE = "AYUDANTE"
    ANALISTA = "ANALISTA"


class CategoriaEquipo(str, enum.Enum):
    SENIOR = "SENIOR"
    JUVENIL = "JUVENIL"
    CADETE = "CADETE"
    INFANTIL = "INFANTIL"
    ALEVIN = "ALEVIN"
    BENJAMIN = "BENJAMIN"
    OTRO = "OTRO"


class GeneroEquipo(str, enum.Enum):
    MASCULINO = "MASCULINO"
    FEMENINO = "FEMENINO"
    MIXTO = "MIXTO"


class TipoEquipo(str, enum.Enum):
    PROPIO = "PROPIO"
    RIVAL = "RIVAL"


class TipoJugador(str, enum.Enum):
    PROPIO = "PROPIO"
    RIVAL = "RIVAL"


class ManoDominante(str, enum.Enum):
    DERECHA = "DERECHA"
    IZQUIERDA = "IZQUIERDA"
    AMBAS = "AMBAS"
    DESCONOCIDA = "DESCONOCIDA"


class PosicionJugador(str, enum.Enum):
    PORTERO = "PORTERO"
    EXTREMO_IZQUIERDO = "EXTREMO_IZQUIERDO"
    EXTREMO_DERECHO = "EXTREMO_DERECHO"
    LATERAL_IZQUIERDO = "LATERAL_IZQUIERDO"
    LATERAL_DERECHO = "LATERAL_DERECHO"
    CENTRAL = "CENTRAL"
    PIVOTE = "PIVOTE"
    UNIVERSAL = "UNIVERSAL"


class TipoAsignacion(str, enum.Enum):
    """Columna TEXT con CHECK en jugadores_equipos (no es un ENUM nativo)."""

    PRINCIPAL = "PRINCIPAL"
    REFUERZO = "REFUERZO"
    DISPONIBLE = "DISPONIBLE"


class ModoTomaDatos(str, enum.Enum):
    EQUIPO_PROPIO = "EQUIPO_PROPIO"
    SCOUTING_COMPLETO = "SCOUTING_COMPLETO"


class TipoLocalizacionPartido(str, enum.Enum):
    LOCAL = "LOCAL"
    VISITANTE = "VISITANTE"
    NEUTRAL = "NEUTRAL"


class EstadoPartido(str, enum.Enum):
    PROGRAMADO = "PROGRAMADO"
    EN_DIRECTO = "EN_DIRECTO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"
    APLAZADO = "APLAZADO"


class OrigenEvento(str, enum.Enum):
    EQUIPO_PROPIO = "EQUIPO_PROPIO"
    RIVAL = "RIVAL"


class PeriodoPartido(str, enum.Enum):
    PRIMERA_PARTE = "PRIMERA_PARTE"
    SEGUNDA_PARTE = "SEGUNDA_PARTE"
    PRORROGA_1 = "PRORROGA_1"
    PRORROGA_2 = "PRORROGA_2"
    PENALTIS = "PENALTIS"


class TipoEvento(str, enum.Enum):
    """Coincide con el ENUM `tipo_evento` de db/schema.sql.

    Los lanzamientos (propios o rivales) siempre se registran con
    tipo=LANZAMIENTO y el resultado se matiza en `resultado_lanzamiento`
    (GOL, PARADA, PALO, FUERA, BLOCADO, ERROR_TECNICO) — ver los ejemplos
    documentados junto a la tabla eventos_partido en schema.sql.
    """

    LANZAMIENTO = "LANZAMIENTO"
    GOL = "GOL"
    PARADA = "PARADA"
    PERDIDA = "PERDIDA"
    ROBO = "ROBO"
    BLOCAJE = "BLOCAJE"
    ASISTENCIA = "ASISTENCIA"
    ERROR_TECNICO = "ERROR_TECNICO"
    FALTA_COMETIDA = "FALTA_COMETIDA"
    FALTA_RECIBIDA = "FALTA_RECIBIDA"
    SIETE_METROS_PROVOCADO = "SIETE_METROS_PROVOCADO"
    SIETE_METROS_COMETIDO = "SIETE_METROS_COMETIDO"
    DOS_MINUTOS = "DOS_MINUTOS"
    TARJETA_AMARILLA = "TARJETA_AMARILLA"
    TARJETA_ROJA = "TARJETA_ROJA"
    TARJETA_AZUL = "TARJETA_AZUL"
    TIEMPO_MUERTO = "TIEMPO_MUERTO"
    CAMBIO = "CAMBIO"
    PASIVO = "PASIVO"
    REBOTE = "REBOTE"
    CAMBIO_SISTEMA = "CAMBIO_SISTEMA"
    INICIO_PERIODO = "INICIO_PERIODO"
    FIN_PERIODO = "FIN_PERIODO"
    INICIO_PARTIDO = "INICIO_PARTIDO"
    FIN_PARTIDO = "FIN_PARTIDO"
    OTRO = "OTRO"


class ResultadoLanzamiento(str, enum.Enum):
    GOL = "GOL"
    PARADA = "PARADA"
    PALO = "PALO"
    FUERA = "FUERA"
    BLOCADO = "BLOCADO"
    ERROR_TECNICO = "ERROR_TECNICO"


class ResultadoEvento(str, enum.Enum):
    EXITO = "EXITO"
    FALLO = "FALLO"
    NEUTRO = "NEUTRO"


class FaseJuego(str, enum.Enum):
    CONTRAATAQUE_PRIMERA_OLEADA = "CONTRAATAQUE_PRIMERA_OLEADA"
    CONTRAATAQUE_SEGUNDA_OLEADA = "CONTRAATAQUE_SEGUNDA_OLEADA"
    ATAQUE_POSICIONAL = "ATAQUE_POSICIONAL"
    SAQUE_CENTRO_RAPIDO = "SAQUE_CENTRO_RAPIDO"
    SIETE_METROS = "SIETE_METROS"
    GOLPE_FRANCO = "GOLPE_FRANCO"
    ATAQUE_PORTERIA_VACIA = "ATAQUE_PORTERIA_VACIA"
    TRANSICION_DEFENSIVA = "TRANSICION_DEFENSIVA"
    DEFENSA_POSICIONAL = "DEFENSA_POSICIONAL"
    ATAQUE_SUPERIORIDAD = "ATAQUE_SUPERIORIDAD"
    ATAQUE_INFERIORIDAD = "ATAQUE_INFERIORIDAD"
    DEFENSA_SUPERIORIDAD = "DEFENSA_SUPERIORIDAD"
    DEFENSA_INFERIORIDAD = "DEFENSA_INFERIORIDAD"
    ATAQUE_7_VS_6 = "ATAQUE_7_VS_6"
    DEFENSA_7_VS_6 = "DEFENSA_7_VS_6"
    OTRA = "OTRA"


class SituacionNumerica(str, enum.Enum):
    SEIS_VS_SEIS = "SEIS_VS_SEIS"
    SEIS_VS_CINCO = "SEIS_VS_CINCO"
    CINCO_VS_SEIS = "CINCO_VS_SEIS"
    SIETE_VS_SEIS = "SIETE_VS_SEIS"
    SEIS_VS_SIETE = "SEIS_VS_SIETE"
    CINCO_VS_CINCO = "CINCO_VS_CINCO"
    OTRA = "OTRA"


class SistemaAtaque(str, enum.Enum):
    TRES_TRES = "TRES_TRES"
    DOS_CUATRO = "DOS_CUATRO"
    SIETE_VS_SEIS = "SIETE_VS_SEIS"
    PORTERIA_VACIA = "PORTERIA_VACIA"
    DESCONOCIDO = "DESCONOCIDO"


class SistemaDefensa(str, enum.Enum):
    SEIS_CERO = "SEIS_CERO"
    CINCO_UNO = "CINCO_UNO"
    TRES_DOS_UNO = "TRES_DOS_UNO"
    CUATRO_DOS = "CUATRO_DOS"
    TRES_TRES = "TRES_TRES"
    MIXTA = "MIXTA"
    INDIVIDUAL = "INDIVIDUAL"
    DESCONOCIDA = "DESCONOCIDA"


class TipoLanzamiento(str, enum.Enum):
    LANZAMIENTO_SUSPENSION = "LANZAMIENTO_SUSPENSION"
    LANZAMIENTO_APOYO = "LANZAMIENTO_APOYO"
    LANZAMIENTO_EXTREMO = "LANZAMIENTO_EXTREMO"
    LANZAMIENTO_PIVOTE = "LANZAMIENTO_PIVOTE"
    LANZAMIENTO_CONTRAATAQUE = "LANZAMIENTO_CONTRAATAQUE"
    LANZAMIENTO_SIETE_METROS = "LANZAMIENTO_SIETE_METROS"
    LANZAMIENTO_PORTERIA_VACIA = "LANZAMIENTO_PORTERIA_VACIA"
    GOLPE_FRANCO_DIRECTO = "GOLPE_FRANCO_DIRECTO"
    OTRO = "OTRO"


class ZonaCampo(str, enum.Enum):
    EXTREMO_IZQUIERDO = "EXTREMO_IZQUIERDO"
    LATERAL_IZQUIERDO_9M = "LATERAL_IZQUIERDO_9M"
    CENTRAL_9M = "CENTRAL_9M"
    LATERAL_DERECHO_9M = "LATERAL_DERECHO_9M"
    EXTREMO_DERECHO = "EXTREMO_DERECHO"
    IZQUIERDA_6M = "IZQUIERDA_6M"
    CENTRO_6M = "CENTRO_6M"
    DERECHA_6M = "DERECHA_6M"
    ZONA_PIVOTE = "ZONA_PIVOTE"
    SIETE_METROS = "SIETE_METROS"
    CAMPO_PROPIO = "CAMPO_PROPIO"
    PORTERIA_VACIA_LARGA_DISTANCIA = "PORTERIA_VACIA_LARGA_DISTANCIA"
    DESCONOCIDA = "DESCONOCIDA"


class ZonaPorteria(str, enum.Enum):
    ALTA_IZQUIERDA = "ALTA_IZQUIERDA"
    ALTA_CENTRO = "ALTA_CENTRO"
    ALTA_DERECHA = "ALTA_DERECHA"
    MEDIA_IZQUIERDA = "MEDIA_IZQUIERDA"
    MEDIA_CENTRO = "MEDIA_CENTRO"
    MEDIA_DERECHA = "MEDIA_DERECHA"
    BAJA_IZQUIERDA = "BAJA_IZQUIERDA"
    BAJA_CENTRO = "BAJA_CENTRO"
    BAJA_DERECHA = "BAJA_DERECHA"
    DESCONOCIDA = "DESCONOCIDA"
